//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FreeWheelDBEntities : DbContext
    {
        public FreeWheelDBEntities()
            : base("name=FreeWheelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CELL> CELLS { get; set; }
        public virtual DbSet<MARKET> MARKETs { get; set; }
        public virtual DbSet<MARKET_POP> MARKET_POP { get; set; }
        public virtual DbSet<PROGRAM> PROGRAMs { get; set; }
        public virtual DbSet<STATION> STATIONs { get; set; }
    }
}
