//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRAM
    {
        public int PROGRAM_ID { get; set; }
        public Nullable<int> STATION_ID { get; set; }
        public string PROGRAM_NAME { get; set; }
        public Nullable<System.DateTime> FLIGHT_DATE { get; set; }
    }
}
